Vagrant.configure("2") do |config|
  config.vm.synced_folder "../../modules", "/tmp/other_modules"
  # config.vm.network :forwarded_port, guest: 22, host: 2223, id: 'ssh'
  config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
  config.vm.provision "shell",
    inline: "puppet apply --modulepath /tmp/other_modules:/vagrant/.fixtures/mymodules /vagrant/examples/example1.pp"
end
